#!/usr/bin/env bash
set -e
eww close-all
pushd /etc/nixos
sudo git diff -U0 *.nix
echo "NixOS Rebuilding..."
sudo nixos-rebuild switch &>nixos-switch.log || (sudo cat nixos-switch.log | grep --color error && false)
current=$(nixos-rebuild list-generations | grep current)
sudo git commit -am "$current"
echo "NixOS Rebuild Successful!"
popd
eww open systembar
