#!/usr/bin/env bash
set -e
eww close-all

git diff -U0 *.nix
echo "NixOS Rebuilding..."
sudo nixos-rebuild switch --flake . &>nixos-switch.log || (cat nixos-switch.log | grep --color error && false)
current=$(nixos-rebuild list-generations | grep current)
git commit -am "$current"
echo "NixOS Rebuild Successful!"

eww open systembar
